-- Tests for the pico-8 style song text parser (data/lib/sfx.lua).

local sfx = require "sfx"

describe("sfx.parse_data", function()
  it("parses a note and a volume", function()
    local d = sfx.parse_data("c-3 a0")
    eq(d[1], 48)
    eq(d[2], 0xa0)
  end)

  it("parses a rest and a note off", function()
    local d = sfx.parse_data("... ..")
    eq(d[1], false)
    eq(d[2], false)
    d = sfx.parse_data("=== ..")
    eq(d[1], -1)
    eq(d[2], false)
  end)

  it("skips empty input", function()
    eq(#sfx.parse_data(""), 0)
    eq(#sfx.parse_data("   "), 0)
    eq(#sfx.parse_data("\t "), 0)
  end)

  it("ignores surrounding whitespace", function()
    local d = sfx.parse_data("  c-3 a0  ")
    eq(d[1], 48)
    eq(d[2], 0xa0)
  end)

  it("collapses repeated spaces", function()
    local d = sfx.parse_data("c-3  a0")
    eq(d[1], 48)
    eq(d[2], 0xa0)
  end)

  it("parses a note without a volume", function()
    local d = sfx.parse_data("c-3")
    eq(#d, 1)
    eq(d[1], 48)
  end)

  it("reports a wrong number", function()
    local d, e = sfx.parse_data("c-3 zz")
    eq(d, false)
    ok(e)
  end)
end)

describe("sfx.parse_row", function()
  it("skips empty lines", function()
    eq(#sfx.parse_row("", {}), 0)
    eq(#sfx.parse_row("   ", {}), 0)
    local r = sfx.parse_row("| ", {})
    eq(#r, 0)
  end)

  it("parses a row with an empty track", function()
    local r, e = sfx.parse_row("| c-3 a0 |  | d-3 a0", {})
    ok(r, e)
    eq(#r, 3)
    eq(r[1][1], 48)
    eq(#r[2], 0)
    eq(r[3][1], 50)
  end)

  it("parses a row with a trailing pipe", function()
    local r, e = sfx.parse_row("| c-3 a0 |", {})
    ok(r, e)
    eq(#r, 2)
    eq(r[1][1], 48)
    eq(#r[2], 0)
  end)
end)

describe("sfx.parse_song", function()
  it("accepts empty lines", function()
    local s, e = sfx.parse_song("| c-3 a0\n\n   \n| d-3 a0\n")
    ok(s, e)
  end)

  it("accepts empty tracks", function()
    local s, e = sfx.parse_song("| c-3 a0 |  | d-3 a0\n")
    ok(s, e)
  end)
end)

describe("sfx.parse_songs", function()
  it("keeps a two-digit volume", function()
    local s, e = sfx.parse_songs("song t\n| d-3 0a | ... ..\n")
    ok(s, e)
    eq(s[1].text, "| d-3 0a | ... .. \n")
  end)

  it("pads a one-digit volume with zero", function()
    local s, e = sfx.parse_songs("song t\n| d-3 a | ... ..\n")
    ok(s, e)
    eq(s[1].text, "| d-3 0a | ... .. \n")
  end)
end)
