name: build-windows-sdl3

on:
  workflow_call:
  workflow_dispatch:

env:
  sdl_ver: 3.4.16
  luajit_ver: "2.1"

jobs:
  build:
    name: windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            cmake pkg-config wget \
            gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64

      - name: Cache SDL3 and LuaJIT
        uses: actions/cache@v6
        with:
          path: external
          key: ${{ runner.os }}-sdl3-win-${{ env.sdl_ver }}-${{ env.luajit_ver }}-${{ hashFiles('contrib/build-rein-sdl3.sh') }}

      - name: Build
        run: sh contrib/build-rein-sdl3.sh windows

      - uses: actions/upload-artifact@v7
        with:
          name: rein-sdl3-windows-x86_64
          path: dist/windows
          if-no-files-found: error
